- hosts: all
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Apache
    yum:
      name: httpd
      state: latest    

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started     

  - name: Enable service httpd, and not touch the state
    ansible.builtin.service:
      name: httpd
      enabled: yes

  - name: Download Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/oxer.zip
      dest: /var/www/html
    
  - name: Extract Template
    unarchive:
      src: /var/www/html/oxer.zip
      dest: /tmp/
      remote_src: yes

  - name: Move Template file to /var/www/html
    shell: "mv /tmp/oxer-html/* /var/www/html/"
    args: 
      creates: /var/www/html/about.html